import type { NodeDefinition } from "./types";

/** 엔진 미연결 시 사용할 기본 노드 정의.
 *
 *  ⚠️ 이 파일은 자동 생성된다 — 직접 고치지 마라.
 *  진실원천은 `nodes/<id>/node.yaml`이고, 바꾼 뒤 `npm run gen:nodes`로 재생성한다.
 */
export const DEFAULT_NODE_DEFINITIONS: NodeDefinition[] = [
  // ─── 변환 ───────────────────────
  {
    id: "docx_to_md", name: "DOCX → 마크다운", version: "1.0.0",
    category: "변환", icon: "file-text", author: "신병철",
    description: "DOCX(Word) 문서를 마크다운 텍스트로 변환한다. kordoc CLI를 우선 사용하고, 실패 시 python-docx로 텍스트를 추출한다.",
    inputs: [{"name": "파일", "type": "file", "accept": [".docx"]}],
    outputs: [{"name": "텍스트", "type": "text"}],
    params: [],
    resource: {"requires_api": null, "max_memory_mb": 200, "estimated_time": "fast"},
    use_when: ["Word 문서의 내용을 읽어야 할 때", "DOCX를 다른 형식으로 변환하기 전 단계로", "Word 문서에서 텍스트를 추출해야 할 때"],
  },
  {
    id: "hwp_to_hwpx", name: "HWP → HWPX 변환", version: "1.0.0",
    category: "변환", icon: "file-text", author: "신병철",
    description: "구형 HWP(바이너리) 파일을 HWPX(XML 기반)로 변환한다. 한/글 COM API를 사용하며 Windows + 한/글 설치 필요. 변환 후 XML 기반 처리(빈칸 추출, 값 주입 등)가 가능해진다.",
    inputs: [{"name": "파일", "type": "file", "accept": [".hwp"]}],
    outputs: [{"name": "파일", "type": "file", "accept": [".hwpx"]}],
    params: [{"id": "output_name", "label": "출력 파일명", "type": "string", "default": "", "description": "비워두면 원본 파일명 사용"}],
    resource: {"max_memory_mb": 200, "estimated_time": "fast"},
    use_when: ["HWP 파일을 HWPX로 변환할 때", "HWP 양식을 XML로 처리하기 위한 사전 변환"],
  },
  {
    id: "hwp_to_md", name: "HWP → 마크다운", version: "1.0.0",
    category: "변환", icon: "file-text", author: "신병철",
    description: "HWP(한글) 문서를 마크다운 텍스트로 변환한다. kordoc CLI를 우선 사용하고, 실패 시 olefile로 텍스트 추출을 시도한다.",
    inputs: [{"name": "파일", "type": "file", "accept": [".hwp"]}],
    outputs: [{"name": "텍스트", "type": "text"}],
    params: [],
    resource: {"requires_api": null, "max_memory_mb": 200, "estimated_time": "fast"},
    use_when: ["HWP 문서의 내용을 읽어야 할 때", "HWP를 다른 형식으로 변환하기 전 단계로", "한글 문서에서 텍스트를 추출해야 할 때"],
  },
  {
    id: "hwpx_to_md", name: "HWPX → 마크다운", version: "1.0.0",
    category: "변환", icon: "file-text", author: "신병철",
    description: "HWPX(한글) 문서를 마크다운 텍스트로 변환한다. kordoc CLI를 우선 사용하고, 실패 시 ZIP 내부 section XML에서 텍스트를 추출한다.",
    inputs: [{"name": "파일", "type": "file", "accept": [".hwpx"]}],
    outputs: [{"name": "텍스트", "type": "text"}],
    params: [],
    resource: {"requires_api": null, "max_memory_mb": 200, "estimated_time": "fast"},
    use_when: ["HWPX 문서의 내용을 읽어야 할 때", "HWPX를 다른 형식으로 변환하기 전 단계로", "한글 문서에서 텍스트를 추출해야 할 때"],
  },
  {
    id: "image_to_text", name: "이미지 → 텍스트 (OCR)", version: "1.0.0",
    category: "변환", icon: "eye", author: "신병철",
    description: "이미지 파일에서 OCR로 텍스트를 추출한다. pytesseract를 사용하며, 한글/영어/일본어를 지원한다.",
    inputs: [{"name": "파일", "type": "file", "accept": [".png", ".jpg", ".jpeg", ".bmp", ".tiff"]}],
    outputs: [{"name": "텍스트", "type": "text"}],
    params: [{"id": "lang", "label": "인식 언어", "type": "select", "default": "kor+eng", "options": ["kor+eng", "eng", "kor", "jpn"], "description": "OCR 인식 언어"}],
    resource: {"requires_api": null, "max_memory_mb": 300, "estimated_time": "medium"},
    use_when: ["이미지에서 텍스트를 추출해야 할 때", "스캔 문서를 텍스트로 변환할 때", "사진 속 글씨를 인식해야 할 때"],
  },
  {
    id: "pdf_to_md", name: "PDF → 마크다운", version: "1.0.0",
    category: "변환", icon: "file-text", author: "신병철",
    description: "PDF 문서를 마크다운 텍스트로 변환한다. 표, 이미지, 텍스트를 구조적으로 추출하여 후속 LLM 처리에 적합한 형태로 출력한다.",
    inputs: [{"name": "파일", "type": "file", "accept": [".pdf"]}],
    outputs: [{"name": "텍스트", "type": "text"}],
    params: [{"id": "pages", "label": "페이지 범위", "type": "string", "default": "전체", "description": "예: 1-5, 3, 10-15"}],
    resource: {"requires_api": null, "max_memory_mb": 200, "estimated_time": "fast"},
    use_when: ["PDF 문서의 내용을 읽어야 할 때", "PDF를 다른 형식으로 변환하기 전 단계로", "문서에서 텍스트를 추출해야 할 때"],
  },
  {
    id: "pptx_to_md", name: "PPTX → 마크다운", version: "1.0.0",
    category: "변환", icon: "file-text", author: "신병철",
    description: "PPTX(파워포인트) 문서를 마크다운 텍스트로 변환한다. 슬라이드별로 ## 헤딩을 붙여 구조적으로 추출한다.",
    inputs: [{"name": "파일", "type": "file", "accept": [".pptx", ".ppt"]}],
    outputs: [{"name": "텍스트", "type": "text"}],
    params: [],
    resource: {"requires_api": null, "max_memory_mb": 200, "estimated_time": "fast"},
    use_when: ["PPTX 문서의 내용을 읽어야 할 때", "파워포인트를 텍스트로 변환할 때", "프레젠테이션에서 텍스트를 추출해야 할 때"],
  },
  {
    id: "url_to_md", name: "URL → 마크다운", version: "1.0.0",
    category: "변환", icon: "globe", author: "신병철",
    description: "웹 URL의 본문을 가져와 마크다운으로 변환한다. requests + BeautifulSoup으로 본문을 추출한다.",
    inputs: [{"name": "URL", "type": "text"}],
    outputs: [{"name": "텍스트", "type": "text"}],
    params: [],
    resource: {"requires_api": null, "max_memory_mb": 100, "estimated_time": "medium"},
    use_when: ["웹 페이지의 내용을 가져와야 할 때", "URL에서 본문 텍스트를 추출할 때", "온라인 문서를 마크다운으로 변환할 때"],
  },
  {
    id: "xlsx_to_md", name: "Excel → 마크다운", version: "1.0.0",
    category: "변환", icon: "table", author: "신병철",
    description: "Excel/CSV 파일을 마크다운 텍스트와 표 데이터로 변환한다. kordoc CLI를 우선 사용하고, 실패 시 pandas로 읽어서 마크다운 표로 출력한다.",
    inputs: [{"name": "파일", "type": "file", "accept": [".xlsx", ".xls", ".csv"]}],
    outputs: [{"name": "텍스트", "type": "text"}, {"name": "표데이터", "type": "table"}],
    params: [{"id": "sheet", "label": "시트명", "type": "string", "default": "", "description": "특정 시트명 (빈값이면 전체 시트)"}],
    resource: {"requires_api": null, "max_memory_mb": 500, "estimated_time": "fast"},
    use_when: ["Excel 파일의 내용을 읽어야 할 때", "스프레드시트 데이터를 텍스트로 변환할 때", "CSV 파일을 구조화된 형태로 변환할 때"],
  },
  // ─── 전처리 ───────────────────────
  {
    id: "column_mapping", name: "컬럼명 매핑", version: "1.0.0",
    category: "전처리", icon: "columns", author: "신병철",
    description: "표 데이터의 컬럼명을 매핑 규칙에 따라 변경한다. \"학번→학생번호, 국→국어점수\" 형태로 지정한다.",
    inputs: [{"name": "표데이터", "type": "table"}],
    outputs: [{"name": "표데이터", "type": "table"}],
    params: [{"id": "mapping_rules", "label": "매핑 규칙", "type": "text", "default": "", "description": "학번→학생번호, 국→국어점수 형태로 입력"}],
    resource: {"requires_api": null, "max_memory_mb": 50, "estimated_time": "fast"},
    use_when: ["표의 컬럼명을 변경해야 할 때", "다른 시스템과 컬럼명을 맞춰야 할 때", "약어를 풀네임으로 변환할 때"],
  },
  {
    id: "data_merge", name: "데이터 병합", version: "1.0.0",
    category: "전처리", icon: "git-merge", author: "신병철",
    description: "여러 표 데이터를 하나로 병합한다. concat(이어붙이기) 또는 merge(키 기준 결합)를 지원한다.",
    inputs: [{"name": "표목록", "type": "table"}],
    outputs: [{"name": "통합표", "type": "table"}],
    params: [{"id": "join_type", "label": "병합 방식", "type": "select", "default": "concat", "options": ["concat", "merge"], "description": "concat: 이어붙이기, merge: 키 기준 결합"}],
    resource: {"requires_api": null, "max_memory_mb": 100, "estimated_time": "fast"},
    use_when: ["여러 표를 하나로 합쳐야 할 때", "시트별 데이터를 통합할 때", "공통 키로 표를 결합할 때"],
  },
  {
    id: "form_extract", name: "양식 빈칸 추출", version: "1.0.0",
    category: "전처리", icon: "scan", author: "신병철",
    description: "HWP/HWPX/XLSX 양식 파일에서 빈칸(입력 필드)을 자동 감지하고, 각 빈칸의 위치·라벨·맥락을 구조화된 JSON으로 추출한다. LLM이 빈칸을 채우기 위한 사전 단계.",
    inputs: [{"name": "파일", "type": "file", "accept": [".hwpx", ".hwp", ".xlsx"]}],
    outputs: [{"name": "빈칸목록", "type": "text"}, {"name": "원본텍스트", "type": "text"}],
    params: [{"id": "include_filled", "label": "이미 채워진 칸도 포함", "type": "boolean", "default": false}],
    resource: {"max_memory_mb": 200, "estimated_time": "fast"},
    use_when: ["공문 첨부 양식의 빈칸을 파악할 때", "양식 파일에서 입력해야 할 항목을 추출할 때"],
  },
  {
    id: "image_extract", name: "이미지 추출", version: "1.0.0",
    category: "전처리", icon: "image", author: "신병철",
    description: "문서 파일(PDF, HWPX, DOCX)에서 이미지를 추출한다. PDF는 pymupdf, 나머지는 ZIP 내 media 폴더에서 추출.",
    inputs: [{"name": "파일", "type": "file", "accept": [".pdf", ".hwpx", ".docx"]}],
    outputs: [{"name": "이미지목록", "type": "list"}],
    params: [{"id": "format", "label": "출력 형식", "type": "select", "default": "png", "options": ["png", "jpg"], "description": "추출 이미지의 저장 형식"}],
    resource: {"requires_api": null, "max_memory_mb": 500, "estimated_time": "medium"},
    use_when: ["문서에서 이미지를 추출해야 할 때", "PDF의 그림을 별도로 저장할 때", "문서 내 이미지를 OCR하기 전 단계로"],
  },
  {
    id: "table_extract", name: "표 추출", version: "1.0.0",
    category: "전처리", icon: "table", author: "신병철",
    description: "마크다운 텍스트에서 표를 추출하여 JSON(list of dict) 형태로 반환한다.",
    inputs: [{"name": "텍스트", "type": "text"}],
    outputs: [{"name": "표데이터", "type": "table"}],
    params: [{"id": "table_index", "label": "표 번호", "type": "integer", "default": 0, "description": "추출할 표 번호 (0부터 시작, -1=모든 표)"}],
    resource: {"requires_api": null, "max_memory_mb": 50, "estimated_time": "fast"},
    use_when: ["마크다운에서 표를 추출해야 할 때", "문서의 표 데이터를 구조화할 때", "표를 JSON이나 엑셀로 변환하기 전 단계로"],
  },
  {
    id: "text_split", name: "텍스트 분할", version: "1.0.0",
    category: "전처리", icon: "scissors", author: "신병철",
    description: "긴 텍스트를 슬라이딩 윈도우 방식으로 지정 크기의 청크로 분할한다.",
    inputs: [{"name": "텍스트", "type": "text"}],
    outputs: [{"name": "청크목록", "type": "list"}],
    params: [{"id": "chunk_size", "label": "청크 크기", "type": "integer", "default": 2000, "description": "각 청크의 최대 글자 수"}, {"id": "overlap", "label": "겹침 크기", "type": "integer", "default": 200, "description": "청크 간 겹치는 글자 수"}],
    resource: {"requires_api": null, "max_memory_mb": 50, "estimated_time": "fast"},
    use_when: ["긴 텍스트를 LLM에 나눠 입력할 때", "문서를 청크 단위로 처리할 때", "RAG용 텍스트 분할이 필요할 때"],
  },
  // ─── LLM ───────────────────────
  {
    id: "llm_classify", name: "LLM 텍스트 분류", version: "1.0.0",
    category: "LLM", icon: "tag", author: "신병철",
    description: "LLM을 사용하여 텍스트를 분류한다. 지정된 카테고리 목록 중 하나로 분류하고 신뢰도를 함께 반환한다.",
    inputs: [{"name": "입력텍스트", "type": "text"}],
    outputs: [{"name": "분류결과", "type": "text"}, {"name": "신뢰도", "type": "text"}],
    params: [{"id": "categories", "label": "카테고리 목록", "type": "text", "default": "수학, 과학, 국어, 영어, 기타", "description": "쉼표로 구분된 카테고리 목록"}, {"id": "provider", "label": "LLM 제공자", "type": "select", "default": "auto", "options": ["auto", "local", "claude", "openai", "gemini"], "description": "auto: API 키 있으면 API, 없으면 로컬"}],
    resource: {"requires_api": null, "max_memory_mb": 2000, "estimated_time": "slow"},
    use_when: ["텍스트를 카테고리별로 분류해야 할 때", "문서의 주제를 판별해야 할 때", "학생 답안의 과목을 자동 분류할 때"],
  },
  {
    id: "llm_extract", name: "LLM 정보 추출", version: "1.0.0",
    category: "LLM", icon: "table", author: "신병철",
    description: "LLM을 사용하여 텍스트에서 지정된 필드를 추출한다. 추출 결과를 표(records: 필드명을 키로 갖는 객체 목록) 형태로 반환하며, 구조화된 데이터 추출에 활용할 수 있다. 로컬 모델도 안정적으로 쓰도록 JSON 스키마 강제 디코딩을 사용한다.",
    inputs: [{"name": "입력텍스트", "type": "text"}],
    outputs: [{"name": "추출결과", "type": "table"}],
    params: [{"id": "fields", "label": "추출 필드", "type": "text", "default": "이름, 학번, 점수", "description": "쉼표로 구분된 추출할 필드 목록"}, {"id": "provider", "label": "LLM 제공자", "type": "select", "default": "auto", "options": ["auto", "local", "claude", "openai", "gemini"], "description": "auto: API 키 있으면 API, 없으면 로컬"}],
    resource: {"requires_api": null, "max_memory_mb": 2000, "estimated_time": "slow"},
    use_when: ["텍스트에서 구조화된 정보를 추출할 때", "비정형 텍스트를 표 형태로 변환할 때", "학생 정보, 성적 등을 텍스트에서 뽑아낼 때"],
  },
  {
    id: "llm_generate", name: "LLM 텍스트 생성", version: "1.0.0",
    category: "LLM", icon: "brain", author: "신병철",
    description: "로컬 LLM 또는 API를 사용하여 텍스트를 생성한다. 프롬프트 템플릿에 입력 텍스트를 삽입하고, LoRA 어댑터 선택으로 작업별 특화 생성이 가능하다.",
    inputs: [{"name": "입력텍스트", "type": "text"}],
    outputs: [{"name": "출력텍스트", "type": "text"}],
    params: [{"id": "prompt_template", "label": "프롬프트 템플릿", "type": "text", "default": "다음 내용을 정리하여 작성하라.\n\n{{입력텍스트}}", "description": "{{변수명}}으로 입력 참조. 여러 줄 가능. {{오늘}}·{{올해}}·{{오늘한글}}은 실제 날짜로 자동 치환된다."}, {"id": "lora", "label": "LoRA 어댑터", "type": "string", "default": "", "description": "비워두면 설정의 기본 어댑터를 사용하고, 'none'이면 어댑터 없이 베이스 모델로 생성한다. 서버 기동 시 프리로드한 어댑터 1개를 켜고 끄는 방식이라 다른 이름을 적어도 교체되지 않는다(설정 > local_lora에서 변경)."}, {"id": "provider", "label": "LLM 제공자", "type": "select", "default": "auto", "options": ["auto", "local", "claude", "openai", "gemini"], "description": "auto: API 키 있으면 API, 없으면 로컬"}, {"id": "max_tokens", "label": "최대 토큰", "type": "integer", "default": 2048, "description": "생성할 최대 토큰 수"}, {"id": "temperature", "label": "온도", "type": "float", "default": 0.7, "description": "0.0(결정적) ~ 1.0(창의적)"}],
    resource: {"requires_api": null, "max_memory_mb": 2000, "estimated_time": "slow"},
    use_when: ["텍스트를 생성해야 할 때", "문서를 요약하거나 변환해야 할 때", "AI가 글을 작성해야 할 때", "공문, 보고서, 상담일지 등을 작성할 때"],
  },
  {
    id: "llm_summarize", name: "LLM 텍스트 요약", version: "1.0.0",
    category: "LLM", icon: "file-text", author: "신병철",
    description: "LLM을 사용하여 텍스트를 요약한다. 글머리 기호, 문단, 한 줄 요약 등 스타일을 선택할 수 있다.",
    inputs: [{"name": "입력텍스트", "type": "text"}],
    outputs: [{"name": "출력텍스트", "type": "text"}],
    params: [{"id": "style", "label": "요약 스타일", "type": "select", "default": "bullet", "options": ["bullet", "paragraph", "oneliner"], "description": "bullet: 글머리 기호, paragraph: 문단, oneliner: 한 줄 요약"}, {"id": "max_length", "label": "최대 길이", "type": "integer", "default": 500, "description": "요약 결과의 최대 글자 수"}, {"id": "provider", "label": "LLM 제공자", "type": "select", "default": "auto", "options": ["auto", "local", "claude", "openai", "gemini"], "description": "auto: API 키 있으면 API, 없으면 로컬"}],
    resource: {"requires_api": null, "max_memory_mb": 2000, "estimated_time": "slow"},
    use_when: ["긴 텍스트를 요약해야 할 때", "문서의 핵심만 추출하고 싶을 때", "회의록, 보고서 등을 간추려야 할 때"],
  },
  {
    id: "llm_translate", name: "LLM 번역", version: "1.0.0",
    category: "LLM", icon: "globe", author: "신병철",
    description: "LLM을 사용하여 텍스트를 번역한다. 영어, 한국어, 일본어, 중국어 중 대상 언어를 선택할 수 있다.",
    inputs: [{"name": "입력텍스트", "type": "text"}],
    outputs: [{"name": "출력텍스트", "type": "text"}],
    params: [{"id": "target_lang", "label": "대상 언어", "type": "select", "default": "영어", "options": ["영어", "한국어", "일본어", "중국어"], "description": "번역할 대상 언어"}, {"id": "provider", "label": "LLM 제공자", "type": "select", "default": "auto", "options": ["auto", "local", "claude", "openai", "gemini"], "description": "auto: API 키 있으면 API, 없으면 로컬"}],
    resource: {"requires_api": null, "max_memory_mb": 2000, "estimated_time": "slow"},
    use_when: ["텍스트를 다른 언어로 번역해야 할 때", "영어 문서를 한국어로 번역할 때", "다국어 자료를 준비할 때"],
  },
  {
    id: "rag_query", name: "RAG 검색 + LLM", version: "1.0.0",
    category: "LLM", icon: "database", author: "신병철",
    description: "질문을 벡터 검색하여 관련 문서 청크를 찾고, 해당 맥락과 함께 LLM에게 답변을 생성시킨다. Retrieval-Augmented Generation (RAG) 파이프라인.",
    inputs: [{"name": "질문", "type": "text"}],
    outputs: [{"name": "답변", "type": "text"}, {"name": "참조문서", "type": "text"}],
    params: [{"id": "n_results", "label": "검색 개수", "type": "integer", "default": 5, "description": "가져올 유사 문서 수"}, {"id": "provider", "label": "LLM", "type": "select", "default": "auto", "options": ["auto", "local", "claude", "openai", "gemini"]}, {"id": "system_prompt", "label": "시스템 프롬프트", "type": "text", "default": "주어진 참조 문서를 바탕으로 질문에 정확히 답하라. 참조 문서에 없는 내용은 추측하지 말고 '정보 없음'이라고 답하라."}, {"id": "max_tokens", "label": "최대 토큰", "type": "integer", "default": 2048}],
    resource: {"requires_api": null, "max_memory_mb": 2000, "estimated_time": "slow"},
    use_when: ["저장된 문서에서 정보를 찾아 답변해야 할 때", "벡터 검색 기반 질의응답이 필요할 때", "임베딩된 데이터를 활용해 정확한 답변을 생성할 때"],
  },
  // ─── 출력 ───────────────────────
  {
    id: "form_fill", name: "양식 값 주입", version: "1.0.0",
    category: "출력", icon: "pen-tool", author: "신병철",
    description: "양식 파일(XLSX/HWPX/HWP)에 값을 주입한다. LLM이 생성한 JSON(빈칸ID→값)을 받아 원본 양식의 해당 위치에 값을 쓴다. 서식, 수식, 매크로를 보존한다.",
    inputs: [{"name": "양식파일", "type": "file", "accept": [".hwpx", ".hwp", ".xlsx"]}, {"name": "채울내용", "type": "text"}],
    outputs: [{"name": "파일", "type": "file"}],
    params: [{"id": "output_name", "label": "출력 파일명", "type": "string", "default": "완성"}],
    resource: {"max_memory_mb": 300, "estimated_time": "fast"},
    use_when: ["양식 파일에 값을 채울 때", "공문 양식을 자동으로 작성할 때", "LLM이 생성한 내용을 원본 파일에 삽입할 때"],
  },
  {
    id: "hwpx_fill", name: "HWPX 양식 채우기", version: "1.0.0",
    category: "출력", icon: "file-check", author: "신병철",
    description: "HWPX 양식 파일의 {{빈칸}} 패턴을 데이터로 치환한다. 표 데이터의 각 행에 대해 별도 파일을 생성한다.",
    inputs: [{"name": "양식파일", "type": "file", "accept": [".hwpx"]}, {"name": "데이터", "type": "table"}],
    outputs: [{"name": "파일", "type": "file", "accept": [".hwpx", ".zip"]}],
    params: [],
    resource: {"requires_api": null, "max_memory_mb": 200, "estimated_time": "fast"},
    use_when: ["HWPX 양식에 데이터를 채워야 할 때", "한글 서식에 자동으로 값을 입력할 때", "양식 문서를 대량 생성할 때"],
  },
  {
    id: "md_to_docx", name: "마크다운 → DOCX", version: "1.0.0",
    category: "출력", icon: "file-output", author: "신병철",
    description: "마크다운 텍스트를 DOCX(Word) 파일로 변환한다. 헤딩, 단락, 표를 지원한다.",
    inputs: [{"name": "텍스트", "type": "text"}],
    outputs: [{"name": "파일", "type": "file", "accept": [".docx"]}],
    params: [{"id": "output_name", "label": "출력 파일명", "type": "string", "default": "output", "description": "확장자 없이 파일명만 입력"}],
    resource: {"requires_api": null, "max_memory_mb": 100, "estimated_time": "fast"},
    use_when: ["마크다운을 Word 문서로 변환할 때", "DOCX 파일을 생성해야 할 때", "결과를 Word 형식으로 저장할 때"],
  },
  {
    id: "md_to_hwpx", name: "마크다운 → HWPX", version: "1.0.0",
    category: "출력", icon: "file-output", author: "신병철",
    description: "마크다운 텍스트를 HWPX(한컴오피스) 파일로 변환한다. 단락, 헤딩, 표를 지원한다.",
    inputs: [{"name": "텍스트", "type": "text"}],
    outputs: [{"name": "파일", "type": "file", "accept": [".hwpx"]}],
    params: [{"id": "output_name", "label": "출력 파일명", "type": "string", "default": "output", "description": "확장자 없이 파일명만 입력"}],
    resource: {"requires_api": null, "max_memory_mb": 100, "estimated_time": "fast"},
    use_when: ["마크다운을 HWPX로 변환할 때", "한글 문서를 생성할 때", "결과를 HWPX 파일로 저장할 때"],
  },
  {
    id: "md_to_pdf", name: "마크다운 → PDF", version: "1.0.0",
    category: "출력", icon: "file-output", author: "신병철",
    description: "마크다운 텍스트를 PDF 파일로 변환한다. 한글 폰트 지원. 표, 제목, 본문 서식 유지.",
    inputs: [{"name": "텍스트", "type": "text"}],
    outputs: [{"name": "파일", "type": "file", "accept": [".pdf"]}],
    params: [{"id": "output_name", "label": "파일명", "type": "string", "default": "output", "description": "출력 파일명 (확장자 제외)"}],
    resource: {"requires_api": null, "max_memory_mb": 200, "estimated_time": "fast"},
    use_when: ["마크다운을 PDF로 변환해야 할 때", "번역이나 요약 결과를 PDF로 저장할 때"],
  },
  {
    id: "save_xlsx", name: "XLSX 저장", version: "1.0.0",
    category: "출력", icon: "file-spreadsheet", author: "신병철",
    description: "표 데이터를 XLSX(엑셀) 파일로 저장한다. pandas DataFrame을 to_excel로 출력한다.",
    inputs: [{"name": "표데이터", "type": "table"}],
    outputs: [{"name": "파일", "type": "file", "accept": [".xlsx"]}],
    params: [{"id": "output_name", "label": "출력 파일명", "type": "string", "default": "output", "description": "확장자 없이 파일명만 입력"}],
    resource: {"requires_api": null, "max_memory_mb": 100, "estimated_time": "fast"},
    use_when: ["표 데이터를 엑셀로 저장할 때", "처리 결과를 스프레드시트로 내보낼 때", "데이터를 XLSX 형식으로 출력할 때"],
  },
  // ─── 유틸 ───────────────────────
  {
    id: "file_input", name: "파일 입력", version: "2.0.0",
    category: "유틸", icon: "file-plus", author: "신병철",
    description: "파일을 입력받아 후속 노드에 전달한다. 자동 변환이 켜져 있으면 PDF/HWPX/DOCX/XLSX 등을 자동으로 마크다운 텍스트로 변환하여 텍스트 출력도 제공한다.",
    inputs: [],
    outputs: [{"name": "파일", "type": "file"}, {"name": "텍스트", "type": "text"}],
    params: [{"id": "path", "label": "파일 경로", "type": "string", "default": "", "description": "파일의 전체 경로"}, {"id": "auto_convert", "label": "자동 텍스트 변환", "type": "boolean", "default": true, "description": "PDF/HWPX/DOCX 등을 자동으로 마크다운으로 변환"}],
    resource: {"requires_api": null, "max_memory_mb": 200, "estimated_time": "fast"},
    use_when: ["파이프라인의 시작점으로 파일을 지정할 때", "파일을 넣으면 자동으로 텍스트가 필요할 때", "LLM에 문서 내용을 바로 전달할 때"],
  },
  {
    id: "rag_ingest", name: "RAG 임베딩 저장", version: "1.0.0",
    category: "유틸", icon: "database", author: "신병철",
    description: "텍스트를 청크로 분할하고 벡터 임베딩으로 변환하여 ChromaDB에 저장한다. 저장된 데이터는 RAG 검색 노드에서 활용된다.",
    inputs: [{"name": "텍스트", "type": "text"}],
    outputs: [{"name": "결과", "type": "text"}],
    params: [{"id": "source_name", "label": "출처 이름", "type": "string", "default": "", "description": "문서 출처 식별용 (예: 2024학년도 수능 수학)"}, {"id": "collection", "label": "컬렉션", "type": "string", "default": "teacherflow", "description": "ChromaDB 컬렉션 이름"}],
    resource: {"requires_api": null, "max_memory_mb": 500, "estimated_time": "medium"},
    use_when: ["문서를 벡터 데이터베이스에 저장해야 할 때", "RAG 검색용 데이터를 준비할 때", "임베딩 데이터를 축적할 때"],
  },
  {
    id: "text_input", name: "텍스트 입력", version: "1.0.0",
    category: "유틸", icon: "type", author: "신병철",
    description: "텍스트를 직접 입력하여 후속 노드에 전달한다.",
    inputs: [],
    outputs: [{"name": "텍스트", "type": "text"}],
    params: [{"id": "content", "label": "내용", "type": "text", "default": "", "description": "전달할 텍스트 내용"}],
    resource: {"requires_api": null, "max_memory_mb": 10, "estimated_time": "fast"},
    use_when: ["파이프라인에 텍스트를 직접 입력할 때", "프롬프트나 지시문을 입력할 때", "고정 텍스트를 후속 노드에 전달할 때"],
  },
  {
    id: "text_template", name: "텍스트 템플릿", version: "1.0.0",
    category: "유틸", icon: "layout-template", author: "신병철",
    description: "템플릿의 {{변수명}}을 입력값으로 치환하여 텍스트를 조합한다.",
    inputs: [{"name": "입력1", "type": "text", "optional": true}, {"name": "입력2", "type": "text", "optional": true}],
    outputs: [{"name": "텍스트", "type": "text"}],
    params: [{"id": "template", "label": "템플릿", "type": "text", "default": "{{입력1}}\n\n---\n\n{{입력2}}", "description": "{{변수명}}으로 입력 참조"}],
    resource: {"requires_api": null, "max_memory_mb": 10, "estimated_time": "fast"},
    use_when: ["여러 텍스트를 하나로 합칠 때", "템플릿에 값을 채워 넣을 때", "프롬프트를 조합할 때"],
  },
];
