import type { NodeDefinition } from "./types";

/** 엔진 미연결 시 사용할 기본 노드 정의 */
export const DEFAULT_NODE_DEFINITIONS: NodeDefinition[] = [
  // ─── 변환 ─────────────────────────────────────
  {
    id: "hwp_to_hwpx", name: "HWP → HWPX 변환", version: "1.0.0",
    category: "변환", icon: "file-text", author: "신병철",
    description: "구형 HWP를 HWPX로 변환. 한/글 COM API 사용 (Windows+한/글 필요).",
    inputs: [{ name: "파일", type: "file", accept: [".hwp"] }],
    outputs: [{ name: "파일", type: "file", accept: [".hwpx"] }],
    params: [{ id: "output_name", label: "출력 파일명", type: "string", default: "" }],
    resource: { max_memory_mb: 200, estimated_time: "fast" },
  },
  {
    id: "pdf_to_md", name: "PDF → 마크다운", version: "1.0.0",
    category: "변환", icon: "file-text", author: "신병철",
    description: "PDF 문서를 마크다운으로 변환. 표·이미지·텍스트 구조적 추출.",
    inputs: [{ name: "파일", type: "file", accept: [".pdf"] }],
    outputs: [{ name: "텍스트", type: "text" }],
    params: [{ id: "pages", label: "페이지 범위", type: "string", default: "전체" }],
    resource: { max_memory_mb: 200, estimated_time: "fast" },
  },
  {
    id: "hwp_to_md", name: "HWP → 마크다운", version: "1.0.0",
    category: "변환", icon: "file-text", author: "신병철",
    description: "구형 HWP(5.x) 문서를 마크다운으로 변환.",
    inputs: [{ name: "파일", type: "file", accept: [".hwp"] }],
    outputs: [{ name: "텍스트", type: "text" }],
    params: [],
    resource: { max_memory_mb: 200, estimated_time: "fast" },
  },
  {
    id: "hwpx_to_md", name: "HWPX → 마크다운", version: "1.0.0",
    category: "변환", icon: "file-text", author: "신병철",
    description: "HWPX(한컴 2020+) 문서를 마크다운으로 변환.",
    inputs: [{ name: "파일", type: "file", accept: [".hwpx"] }],
    outputs: [{ name: "텍스트", type: "text" }],
    params: [],
    resource: { max_memory_mb: 100, estimated_time: "fast" },
  },
  {
    id: "docx_to_md", name: "DOCX → 마크다운", version: "1.0.0",
    category: "변환", icon: "file-text", author: "신병철",
    description: "Word(DOCX) 문서를 마크다운으로 변환. kordoc 활용.",
    inputs: [{ name: "파일", type: "file", accept: [".docx"] }],
    outputs: [{ name: "텍스트", type: "text" }],
    params: [],
    resource: { max_memory_mb: 200, estimated_time: "fast" },
  },
  {
    id: "xlsx_to_md", name: "엑셀 → 마크다운", version: "1.0.0",
    category: "변환", icon: "file-spreadsheet", author: "신병철",
    description: "엑셀 파일을 마크다운 표로 변환.",
    inputs: [{ name: "파일", type: "file", accept: [".xlsx", ".xls", ".csv"] }],
    outputs: [{ name: "텍스트", type: "text" }, { name: "표데이터", type: "table" }],
    params: [{ id: "sheet", label: "시트 이름", type: "string", default: "" }],
    resource: { max_memory_mb: 200, estimated_time: "fast" },
  },
  {
    id: "pptx_to_md", name: "PPT → 마크다운", version: "1.0.0",
    category: "변환", icon: "presentation", author: "신병철",
    description: "파워포인트(PPTX)를 마크다운으로 변환. 슬라이드별 섹션 분리.",
    inputs: [{ name: "파일", type: "file", accept: [".pptx", ".ppt"] }],
    outputs: [{ name: "텍스트", type: "text" }],
    params: [],
    resource: { max_memory_mb: 200, estimated_time: "fast" },
  },
  {
    id: "image_to_text", name: "이미지 → 텍스트", version: "1.0.0",
    category: "변환", icon: "scan", author: "신병철",
    description: "이미지에서 텍스트 추출 (OCR). 스캔 문서·사진 지원.",
    inputs: [{ name: "파일", type: "file", accept: [".png", ".jpg", ".jpeg", ".bmp", ".tiff"] }],
    outputs: [{ name: "텍스트", type: "text" }],
    params: [{ id: "lang", label: "언어", type: "select", default: "kor+eng", options: ["kor+eng", "eng", "kor", "jpn"] }],
    resource: { max_memory_mb: 500, estimated_time: "medium" },
  },
  {
    id: "url_to_md", name: "웹페이지 → 마크다운", version: "1.0.0",
    category: "변환", icon: "globe", author: "신병철",
    description: "URL의 웹페이지 내용을 마크다운으로 변환.",
    inputs: [{ name: "URL", type: "text" }],
    outputs: [{ name: "텍스트", type: "text" }],
    params: [],
    resource: { max_memory_mb: 200, estimated_time: "medium" },
  },

  // ─── 전처리 ───────────────────────────────────
  {
    id: "form_extract", name: "양식 빈칸 추출", version: "1.0.0",
    category: "전처리", icon: "scan", author: "신병철",
    description: "HWP/HWPX/XLSX 양식에서 빈칸을 자동 감지. 위치·라벨·맥락을 JSON으로 추출.",
    inputs: [{ name: "파일", type: "file", accept: [".hwpx", ".hwp", ".xlsx", ".xls"] }],
    outputs: [{ name: "빈칸목록", type: "text" }, { name: "원본텍스트", type: "text" }],
    params: [{ id: "include_filled", label: "이미 채워진 칸도 포함", type: "boolean", default: false }],
    resource: { max_memory_mb: 200, estimated_time: "fast" },
  },
  {
    id: "table_extract", name: "표 추출", version: "1.0.0",
    category: "전처리", icon: "table", author: "신병철",
    description: "마크다운 텍스트에서 표 데이터만 추출.",
    inputs: [{ name: "텍스트", type: "text" }],
    outputs: [{ name: "표데이터", type: "table" }],
    params: [{ id: "table_index", label: "표 번호", type: "integer", default: 0 }],
    resource: { max_memory_mb: 100, estimated_time: "fast" },
  },
  {
    id: "data_merge", name: "데이터 병합", version: "1.0.0",
    category: "전처리", icon: "merge", author: "신병철",
    description: "여러 표 데이터를 하나로 병합.",
    inputs: [{ name: "표목록", type: "list" }],
    outputs: [{ name: "통합표", type: "table" }],
    params: [{ id: "join_type", label: "병합 방식", type: "select", default: "concat", options: ["concat", "merge"] }],
    resource: { max_memory_mb: 200, estimated_time: "fast" },
  },
  {
    id: "column_mapping", name: "컬럼 매핑", version: "1.0.0",
    category: "전처리", icon: "settings", author: "신병철",
    description: "컬럼명을 표준 이름으로 통일. AI 매핑 제안.",
    inputs: [{ name: "표데이터", type: "table" }],
    outputs: [{ name: "표데이터", type: "table" }],
    params: [{ id: "mapping_rules", label: "매핑 규칙", type: "text", default: "" }],
    resource: { max_memory_mb: 100, estimated_time: "fast" },
  },
  {
    id: "text_split", name: "텍스트 분할", version: "1.0.0",
    category: "전처리", icon: "scissors", author: "신병철",
    description: "긴 텍스트를 청크 단위로 분할. LLM 입력 크기 초과 시 유용.",
    inputs: [{ name: "텍스트", type: "text" }],
    outputs: [{ name: "청크목록", type: "list" }],
    params: [
      { id: "chunk_size", label: "청크 크기(자)", type: "integer", default: 2000 },
      { id: "overlap", label: "겹침(자)", type: "integer", default: 200 },
    ],
    resource: { max_memory_mb: 100, estimated_time: "fast" },
  },
  {
    id: "image_extract", name: "이미지 추출", version: "1.0.0",
    category: "전처리", icon: "image", author: "신병철",
    description: "PDF·HWPX 문서에서 이미지만 추출.",
    inputs: [{ name: "파일", type: "file", accept: [".pdf", ".hwpx", ".docx"] }],
    outputs: [{ name: "이미지목록", type: "list" }],
    params: [{ id: "format", label: "출력 형식", type: "select", default: "png", options: ["png", "jpg"] }],
    resource: { max_memory_mb: 300, estimated_time: "medium" },
  },

  // ─── LLM (5개) ────────────────────────────────
  {
    id: "llm_generate", name: "LLM 생성", version: "1.0.0",
    category: "LLM", icon: "brain", author: "신병철",
    description: "프롬프트 템플릿으로 텍스트 생성. {{변수명}} 패턴 지원.",
    inputs: [{ name: "입력텍스트", type: "text" }],
    outputs: [{ name: "출력텍스트", type: "text" }],
    params: [
      { id: "prompt_template", label: "프롬프트", type: "text", default: "다음 내용을 정리하라.\n\n{{입력텍스트}}" },
      { id: "provider", label: "LLM", type: "select", default: "auto", options: ["auto", "local", "claude", "openai", "gemini"] },
      { id: "max_tokens", label: "최대 토큰", type: "integer", default: 2048 },
      { id: "temperature", label: "온도", type: "float", default: 0.7 },
    ],
    resource: { max_memory_mb: 2000, estimated_time: "slow" },
  },
  {
    id: "llm_summarize", name: "LLM 요약", version: "1.0.0",
    category: "LLM", icon: "sparkles", author: "신병철",
    description: "긴 텍스트를 자동 요약.",
    inputs: [{ name: "입력텍스트", type: "text" }],
    outputs: [{ name: "출력텍스트", type: "text" }],
    params: [
      { id: "style", label: "스타일", type: "select", default: "bullet", options: ["bullet", "paragraph", "oneliner"] },
      { id: "max_length", label: "최대 길이", type: "integer", default: 500 },
    ],
    resource: { max_memory_mb: 2000, estimated_time: "slow" },
  },
  {
    id: "llm_classify", name: "LLM 분류", version: "1.0.0",
    category: "LLM", icon: "tag", author: "신병철",
    description: "텍스트를 지정한 카테고리로 자동 분류.",
    inputs: [{ name: "입력텍스트", type: "text" }],
    outputs: [{ name: "분류결과", type: "text" }, { name: "신뢰도", type: "text" }],
    params: [
      { id: "categories", label: "분류 항목", type: "text", default: "수학, 과학, 국어, 영어, 기타" },
    ],
    resource: { max_memory_mb: 2000, estimated_time: "slow" },
  },
  {
    id: "llm_translate", name: "LLM 번역", version: "1.0.0",
    category: "LLM", icon: "languages", author: "신병철",
    description: "텍스트를 지정 언어로 번역.",
    inputs: [{ name: "입력텍스트", type: "text" }],
    outputs: [{ name: "출력텍스트", type: "text" }],
    params: [
      { id: "target_lang", label: "대상 언어", type: "select", default: "영어", options: ["영어", "한국어", "일본어", "중국어"] },
    ],
    resource: { max_memory_mb: 2000, estimated_time: "slow" },
  },
  {
    id: "llm_extract", name: "LLM 정보 추출", version: "1.0.0",
    category: "LLM", icon: "scan", author: "신병철",
    description: "텍스트에서 지정 항목(이름, 날짜, 점수 등)을 구조적으로 추출.",
    inputs: [{ name: "입력텍스트", type: "text" }],
    outputs: [{ name: "추출결과", type: "table" }],
    params: [
      { id: "fields", label: "추출 항목", type: "text", default: "이름, 학번, 점수" },
    ],
    resource: { max_memory_mb: 2000, estimated_time: "slow" },
  },

  // ─── 출력 ─────────────────────────────────────
  {
    id: "form_fill", name: "양식 값 주입", version: "1.0.0",
    category: "출력", icon: "pen-tool", author: "신병철",
    description: "양식 파일(XLSX/HWPX/HWP)에 값을 주입. 서식·수식·매크로 보존.",
    inputs: [
      { name: "양식파일", type: "file", accept: [".hwpx", ".hwp", ".xlsx", ".xls"] },
      { name: "채울내용", type: "text" },
    ],
    outputs: [{ name: "파일", type: "file" }],
    params: [{ id: "output_name", label: "출력 파일명", type: "string", default: "완성" }],
    resource: { max_memory_mb: 300, estimated_time: "fast" },
  },
  {
    id: "md_to_hwpx", name: "마크다운 → HWPX", version: "1.0.0",
    category: "출력", icon: "file-output", author: "신병철",
    description: "마크다운을 HWPX(한컴오피스) 파일로 변환.",
    inputs: [{ name: "텍스트", type: "text" }],
    outputs: [{ name: "파일", type: "file", accept: [".hwpx"] }],
    params: [{ id: "output_name", label: "파일명", type: "string", default: "output" }],
    resource: { max_memory_mb: 100, estimated_time: "fast" },
  },
  {
    id: "md_to_docx", name: "마크다운 → DOCX", version: "1.0.0",
    category: "출력", icon: "file-output", author: "신병철",
    description: "마크다운을 Word(DOCX) 파일로 변환.",
    inputs: [{ name: "텍스트", type: "text" }],
    outputs: [{ name: "파일", type: "file", accept: [".docx"] }],
    params: [{ id: "output_name", label: "파일명", type: "string", default: "output" }],
    resource: { max_memory_mb: 100, estimated_time: "fast" },
  },
  {
    id: "save_xlsx", name: "엑셀 저장", version: "1.0.0",
    category: "출력", icon: "file-spreadsheet", author: "신병철",
    description: "표 데이터를 엑셀 파일로 저장.",
    inputs: [{ name: "표데이터", type: "table" }],
    outputs: [{ name: "파일", type: "file", accept: [".xlsx"] }],
    params: [{ id: "output_name", label: "파일명", type: "string", default: "output" }],
    resource: { max_memory_mb: 100, estimated_time: "fast" },
  },
  {
    id: "md_to_pdf", name: "마크다운 → PDF", version: "1.0.0",
    category: "출력", icon: "file-output", author: "신병철",
    description: "마크다운을 PDF 파일로 변환. 한글 폰트 지원.",
    inputs: [{ name: "텍스트", type: "text" }],
    outputs: [{ name: "파일", type: "file", accept: [".pdf"] }],
    params: [{ id: "output_name", label: "파일명", type: "string", default: "output" }],
    resource: { max_memory_mb: 200, estimated_time: "fast" },
  },
  {
    id: "hwpx_fill", name: "HWPX 양식 채우기", version: "1.0.0",
    category: "출력", icon: "pen-tool", author: "신병철",
    description: "HWPX 양식의 빈칸을 자동 감지·채우기. 원본 서식 100% 유지.",
    inputs: [
      { name: "양식파일", type: "file", accept: [".hwpx"] },
      { name: "데이터", type: "table" },
    ],
    outputs: [{ name: "파일", type: "file", accept: [".hwpx"] }],
    params: [],
    resource: { max_memory_mb: 100, estimated_time: "fast" },
  },

  // ─── RAG (2개) ─────────────────────────────────
  {
    id: "rag_ingest", name: "RAG 임베딩 저장", version: "1.0.0",
    category: "유틸", icon: "database", author: "신병철",
    description: "텍스트를 청크 분할 → 벡터 임베딩 → ChromaDB 저장. RAG 검색 데이터 준비.",
    inputs: [{ name: "텍스트", type: "text" }],
    outputs: [{ name: "결과", type: "text" }],
    params: [
      { id: "source_name", label: "출처 이름", type: "string", default: "" },
      { id: "collection", label: "컬렉션", type: "string", default: "teacherflow" },
    ],
    resource: { max_memory_mb: 500, estimated_time: "medium" },
  },
  {
    id: "rag_query", name: "RAG 검색 + LLM", version: "1.0.0",
    category: "LLM", icon: "database", author: "신병철",
    description: "질문 → 벡터 검색 → 관련 문서 + LLM 답변 생성 (RAG 파이프라인).",
    inputs: [{ name: "질문", type: "text" }],
    outputs: [{ name: "답변", type: "text" }, { name: "참조문서", type: "text" }],
    params: [
      { id: "n_results", label: "검색 개수", type: "integer", default: 5 },
      { id: "provider", label: "LLM", type: "select", default: "auto", options: ["auto", "local", "claude", "openai", "gemini"] },
      { id: "system_prompt", label: "시스템 프롬프트", type: "text", default: "주어진 참조 문서를 바탕으로 질문에 정확히 답하라." },
      { id: "max_tokens", label: "최대 토큰", type: "integer", default: 2048 },
    ],
    resource: { max_memory_mb: 2000, estimated_time: "slow" },
  },

  // ─── 유틸 (3개) ───────────────────────────────
  {
    id: "file_input", name: "파일 입력", version: "2.0.0",
    category: "유틸", icon: "upload", author: "신병철",
    description: "파일을 입력. 자동 변환 ON이면 PDF/HWPX/DOCX 등을 텍스트로도 출력.",
    inputs: [],
    outputs: [{ name: "파일", type: "file" }, { name: "텍스트", type: "text" }],
    params: [
      { id: "path", label: "파일 경로", type: "string", default: "" },
      { id: "auto_convert", label: "자동 텍스트 변환", type: "boolean", default: true },
    ],
    resource: { max_memory_mb: 200, estimated_time: "fast" },
  },
  {
    id: "text_input", name: "텍스트 입력", version: "1.0.0",
    category: "유틸", icon: "type", author: "신병철",
    description: "워크플로우 시작점. 텍스트를 직접 입력.",
    inputs: [],
    outputs: [{ name: "텍스트", type: "text" }],
    params: [{ id: "content", label: "내용", type: "text", default: "" }],
    resource: { max_memory_mb: 10, estimated_time: "fast" },
  },
  {
    id: "text_template", name: "텍스트 템플릿", version: "1.0.0",
    category: "유틸", icon: "layout", author: "신병철",
    description: "여러 입력을 하나의 텍스트 템플릿으로 합침. {{변수}} 치환.",
    inputs: [{ name: "입력1", type: "text" }, { name: "입력2", type: "text" }],
    outputs: [{ name: "텍스트", type: "text" }],
    params: [{ id: "template", label: "템플릿", type: "text", default: "{{입력1}}\n\n---\n\n{{입력2}}" }],
    resource: { max_memory_mb: 10, estimated_time: "fast" },
  },
];
